{% set name = "chemper" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mobleylab/chemper/archive/{{ version }}.tar.gz
  sha256: bbc1f587ef01317c4592c6e8b0fd728215eea0e995f547e05d71232cf017531e


build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - numpy
    - python
    - rdkit
    - networkx

test:
  imports:
    - chemper
  requires:
    - pip
  commands:
    - pip check
    - python -c "import chemper; print(chemper.__version__)"

about:
  home: https://github.com/mobleylab/chemper
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Chemical Perception Sampling Tools
  doc_url: https://chemper.readthedocs.io/
  dev_url: https://github.com/mobleylab/chemper

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
    - dotsdl
    - jaimergp
    - jthorton
